Привет, меня зовут Артем Хуршудов. Сегодня я проверю твой проект.
<br> Дальнейшее общение будет происходить на "ты" если это не вызывает никаких проблем.
<br> Желательно реагировать на каждый мой комментарий ('исправил', 'не понятно как исправить ошибку', ...)
<br> Пожалуйста, не удаляй комментарии ревьюера, так как они повышают качество повторного ревью.

Комментарии будут в <font color='green'>зеленой</font>, <font color='blue'>синей</font> или <font color='red'>красной</font> рамках:

<div class="alert alert-block alert-success">
<b>Успех:</b> Если все сделано отлично
</div>

<div class="alert alert-block alert-info">
<b>Совет: </b> Если можно немного улучшить
</div>

<div class="alert alert-block alert-danger">
<b>Ошибка:</b> Если требуются исправления. Работа не может быть принята с красными комментариями.
</div>

-------------------

Будет очень хорошо, если ты будешь помечать свои действия следующим образом:
<div class="alert alert-block alert-warning">
<b>Комментарий студента:</b> ...
</div>

<div class="alert alert-block alert-warning">
<b>Изменения:</b> Были внесены следующие изменения ...
</div>

#### <font color='orange'>Полезные ссылки:</font>
* Могу предложить обратить внимание на вот этот теоритический курс лекций: https://www.youtube.com/watch?v=SZkrxWhI5qM&list=PLJOzdkh8T5krxc4HsHbB8g8f0hu7973fK

### <font color='orange'>Общее впечатление</font>
* Большое спасибо за проделанную работу. Видно, что приложено много усилий.
* Отлично, что правильно использованы train/valid/test наборы.
* Выводы и рассуждения получились содержательными, их было интересно читать.
* Я оставил несколько советов, надеюсь, что они будут учтены в будущих проектах.
* Тебе удалось добиться очень хорошего качества, поздравляю!
* Проект может быть зачтен, но я его отправлю назад, чтобы у тебя была возможность задать вопросы и внести правки, при желании. Однако, ты можешь просто вернуть проект в таком же виде и я его зачту.

### <font color='orange'>Общее впечатление (ревью 2)</font>
* Проект зачтен!
* Для удобства все новые комментарии обозначены фразой "ревью 2".
* Удачи в дальнейшем обучении и следующих работах!

# Рекомендации тарифов для оператора мобильной связи «Мегалайн» <br>
*Оператор мобильной связи «Мегалайн» выяснил: многие клиенты пользуются архивными тарифами. Они хотят построить систему, способную проанализировать поведение клиентов и предложить пользователям новый тариф: «Смарт» или «Ультра».
В вашем распоряжении данные о поведении клиентов, которые уже перешли на эти тарифы (из проекта курса «Статистический анализ данных»). Нужно построить модель для задачи классификации, которая выберет подходящий тариф. Предобработка данных не понадобится — вы её уже сделали.
Постройте модель с максимально большим значением accuracy. Чтобы сдать проект успешно, нужно довести долю правильных ответов по крайней мере до 0.75. Проверьте accuracy на тестовой выборке самостоятельно.* <br> <br>
**Описание данных** <br> <br>
*Каждый объект в наборе данных — это информация о поведении одного пользователя за месяц. Известно:*<br>

*сalls — количество звонков,*<br>
*minutes — суммарная длительность звонков в минутах,*<br>
*messages — количество sms-сообщений,*<br>
*mb_used — израсходованный интернет-трафик в Мб,*<br>
*is_ultra — каким тарифом пользовался в течение месяца («Ультра» — 1, «Смарт» — 0).*<br>

<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Полезные-ссылки:" data-toc-modified-id="Полезные-ссылки:-0.0.1"><span class="toc-item-num">0.0.1&nbsp;&nbsp;</span><font color="orange">Полезные ссылки:</font></a></span></li></ul></li><li><span><a href="#Общее-впечатление" data-toc-modified-id="Общее-впечатление-0.1"><span class="toc-item-num">0.1&nbsp;&nbsp;</span><font color="orange">Общее впечатление</font></a></span></li><li><span><a href="#Общее-впечатление-(ревью-2)" data-toc-modified-id="Общее-впечатление-(ревью-2)-0.2"><span class="toc-item-num">0.2&nbsp;&nbsp;</span><font color="orange">Общее впечатление (ревью 2)</font></a></span></li></ul></li><li><span><a href="#Знакомство-с-данными" data-toc-modified-id="Знакомство-с-данными-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Знакомство с данными</a></span><ul class="toc-item"><li><span><a href="#Импорт-библиотек" data-toc-modified-id="Импорт-библиотек-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Импорт библиотек</a></span></li><li><span><a href="#Чтение-данных" data-toc-modified-id="Чтение-данных-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Чтение данных</a></span></li><li><span><a href="#Изменение-типа-данных" data-toc-modified-id="Изменение-типа-данных-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Изменение типа данных</a></span></li><li><span><a href="#Анализ-данных" data-toc-modified-id="Анализ-данных-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Анализ данных</a></span></li></ul></li><li><span><a href="#Разбивка-данных-по-выборкам" data-toc-modified-id="Разбивка-данных-по-выборкам-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Разбивка данных по выборкам</a></span><ul class="toc-item"><li><span><a href="#Признаки-'features'-и-целевой-признак-'target'" data-toc-modified-id="Признаки-'features'-и-целевой-признак-'target'-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Признаки 'features' и целевой признак 'target'</a></span></li><li><span><a href="#Выделение-тестовой-выборки-из-общей" data-toc-modified-id="Выделение-тестовой-выборки-из-общей-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Выделение тестовой выборки из общей</a></span></li><li><span><a href="#Выделение-валидационной-выборки-из-тестовой" data-toc-modified-id="Выделение-валидационной-выборки-из-тестовой-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Выделение валидационной выборки из тестовой</a></span></li></ul></li><li><span><a href="#Исследование-моделей" data-toc-modified-id="Исследование-моделей-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Исследование моделей</a></span><ul class="toc-item"><li><span><a href="#Дерево-решений" data-toc-modified-id="Дерево-решений-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Дерево решений</a></span></li><li><span><a href="#Случайный-лес" data-toc-modified-id="Случайный-лес-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Случайный лес</a></span></li><li><span><a href="#Логистическая-регрессия" data-toc-modified-id="Логистическая-регрессия-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Логистическая регрессия</a></span></li></ul></li><li><span><a href="#Проверка-моделей-на-тестовой-выборке" data-toc-modified-id="Проверка-моделей-на-тестовой-выборке-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка моделей на тестовой выборке</a></span><ul class="toc-item"><li><span><a href="#Дерево-решений" data-toc-modified-id="Дерево-решений-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Дерево решений</a></span></li><li><span><a href="#Случайный-лес" data-toc-modified-id="Случайный-лес-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Случайный лес</a></span></li></ul></li><li><span><a href="#Проверка-модели-на-адекватность" data-toc-modified-id="Проверка-модели-на-адекватность-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Проверка модели на адекватность</a></span></li><li><span><a href="#Общий-вывод" data-toc-modified-id="Общий-вывод-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Общий вывод</a></span></li></ul></div>

## Знакомство с данными

### Импорт библиотек

In [1]:
import pandas as pd                                   # импорт библиотеки pandas
import numpy as np                                    # импорт библиотеки numpy
from scipy import stats as st                         # импорт библиотеки scipy
from IPython.display import display_html              # импорт модуля display_html из библиотеки IPython
from IPython.core.display import display, HTML        # импорт display, HTML из библиотеки IPython
from sklearn.tree import DecisionTreeClassifier       # импорт алгоритма решающего дерева из библиотеки sklearn
from sklearn.ensemble import RandomForestClassifier   # импорт алгоритма случайный лес из библиотеки sklearn
from sklearn.linear_model import LogisticRegression   # импорт алгоритма логистическая регрессия из библиотеки sklearn
from sklearn.model_selection import train_test_split  # импорт функции train_test_split из библиотеки sklearn
from sklearn.metrics import accuracy_score            # импорт функции расчёта accuracy из библиотеки sklearn
from sklearn.metrics import mean_squared_error        # импорт функции расчёта mean_squared_error из библиотеки sklearn
import joblib                                         # импорт библиотеки joblib
from joblib import dump                               # импорт функции dump библиотеки joblib
import warnings                                       # импорт warnings
import matplotlib.pyplot as plt                       # импорт модуля pyplot из библиотеки matplotlib  
import seaborn as sns                                 # импорт библиотеки seaborn
import os

<div class="alert alert-block alert-info">
<b>Совет: </b> Желательно чтобы все импорты были собраны в первой ячейке ноутбука! Если у того, кто будет запускать твой ноутбук будут отсутствовать некоторые библиотеки, то он это увидит сразу, а не в процессе!
</div>

<div class="alert alert-block alert-warning">
<b>Изменения:</b> Были внесены следующие изменения - 'import os' перенёс в блок выше
</div>

<div class="alert alert-block alert-info">
<b>Совет (ревью 2): </b> Еще дамми модель.
</div>

### Чтение данных

In [2]:
#import os
pth1 = '/datasets/users_behavior.csv'
pth2 = 'users_behavior.csv'
if os.path.exists(pth1):
    users_behavior_data = pd.read_csv(pth1)
elif os.path.exists(pth2):
    users_behavior_data = pd.read_csv(pth2)
else:
    print("Проверьте правильность пути к датасету")

pd.set_option('display.max_columns', None)                           # Снимем ограничение на количество показываемых столбцов
warnings.filterwarnings('ignore')                                    # Игнорируем предупреждения

In [3]:
users_behavior_data

calls  minutes  messages   mb_used  is_ultra
0      40.0   311.90      83.0  19915.42         0
1      85.0   516.75      56.0  22696.96         0
2      77.0   467.66      86.0  21060.45         0
3     106.0   745.53      81.0   8437.39         1
4      66.0   418.74       1.0  14502.75         0
...     ...      ...       ...       ...       ...
3209  122.0   910.98      20.0  35124.90         1
3210   25.0   190.36       0.0   3275.61         0
3211   97.0   634.44      70.0  13974.06         0
3212   64.0   462.32      90.0  31239.78         0
3213   80.0   566.09       6.0  29480.52         1

[3214 rows x 5 columns]

In [4]:
users_behavior_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3214 entries, 0 to 3213
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   calls     3214 non-null   float64
 1   minutes   3214 non-null   float64
 2   messages  3214 non-null   float64
 3   mb_used   3214 non-null   float64
 4   is_ultra  3214 non-null   int64  
dtypes: float64(4), int64(1)
memory usage: 125.7 KB


**Вывод:**<br>
- Имеется всего 3214 записей без пропусков в 5 категориях. <br>
- Все категории, кроме 'is_ultra', содержат данные типа *float*
- Категории 'calls' и 'messages' содержат данные, которые по природе имеют целочисленный тип данных и значит могут быть сконвертированы в последний для экономии памяти и вычислительного времени.

<div class="alert alert-block alert-success">
<b>Успех:</b> Данные загружены корректно, первичный осмотр проведен.
</div>

### Изменение типа данных

In [5]:
users_behavior_data['calls'] = users_behavior_data['calls'].astype('int')
users_behavior_data['messages'] = users_behavior_data['messages'].astype('int')

### Анализ данных

In [6]:
users_behavior_data.describe()

calls      minutes     messages       mb_used     is_ultra
count  3214.000000  3214.000000  3214.000000   3214.000000  3214.000000
mean     63.038892   438.208787    38.281269  17207.673836     0.306472
std      33.236368   234.569872    36.148326   7570.968246     0.461100
min       0.000000     0.000000     0.000000      0.000000     0.000000
25%      40.000000   274.575000     9.000000  12491.902500     0.000000
50%      62.000000   430.600000    30.000000  16943.235000     0.000000
75%      82.000000   571.927500    57.000000  21424.700000     1.000000
max     244.000000  1632.060000   224.000000  49745.730000     1.000000

**Вывод:** <br>
- Минимальное, нулевое, значение характерно для всех категорий данных <br>
- в категории 'calls' максимальное значение равно 244, медианное значение равно 62, а среднее значение равно 63 <br>
- в категории 'minutes' максимальное значение равно 1632, медианное значение равно 431, а среднее значение равно 438 <br>
- в категории 'messages' максимальное значение равно 244, медианное значение равно 30, а среднее значение равно 38 <br>
- в категории 'mb_used' максимальное значение равно 49746, медианное значение равно 16943, а среднее значение равно 17208 <br>
- категория 'is_ultra' отражает бинарное состояние: пользуется ли тарифом 'ultra' конкретный пользователь. Однако и в этом случае среднее значение 0,31 говорит о том, что  тарифом 'ultra' пользуются около 31% всех пользователей.

In [7]:
# проверим данные на наличие дубликатов
users_behavior_data.duplicated().sum()

0

- Дубликаты не обнаружены

In [8]:
# Проверим, есть ли в данных взаимозависимости параметров.

pd.plotting.scatter_matrix(users_behavior_data,figsize=(20,20))
plt.suptitle("Матрица зависимостей", size=20)
plt.show()

**Вывод** <br>
- согласно графикам есть строгопрослеживаемая связь между количеством минут и количеством звонков у абонентов. Это может негативно сказаться на обучение модели (она может увидеть эту связь и переобучиться). Чтобы убрать возможное негативное влияние уберём из общего набора данные о количестве звонков, т.к. по этому параметру тарификация не идёт (стоимость зависит обслуживания на тарифе зависит от количества минут, а не от количества звонков)

In [9]:
#Удалим данные о количестве минут согласно ранее сделанным выводам
users_behavior_data = users_behavior_data.drop(columns=['calls']) 

<div class="alert alert-block alert-success">
<b>Успех:</b> Радует, что распределения были визуализированы. 
</div>

<div class="alert alert-block alert-success">
<b>Успех:</b> Удалить эту колонку – хорошее решение.
</div>

## Разбивка данных по выборкам

### Признаки 'features' и целевой признак 'target'

In [10]:
features = users_behavior_data.drop(['is_ultra'], axis=1)  #извлекаем признаки
target = users_behavior_data['is_ultra']                   #извлекаем целевой признаки

### Выделение тестовой выборки из общей

*После создания 'features' и 'target' необходимо разделить выборку на треннировочную, валидационную и тестовую. Разделим их в соотношении 3/5 - 1/5 - 1/5, соответственно.* <br>
*Для этого последовательно применим 'train_test_split' сначала для разделения на треннировочную и тестовую выборки, а затем выделим из тестовой выборки валидационную.*

In [11]:
#Разделим общую выборку на целевую и тестовую в соотношении 60% на 40%, т.к. 
#далее разделим тестовую выборку на тестовую и валидационную
features_train, features_test, target_train, target_test = train_test_split(
    features, target, train_size=0.60,random_state=12345)

print(f'Размер массива целевых значений обучающей выборки:{target_train.shape}')
print(f'Размер массива целевых значений тестовой выборки: {target_test.shape}')
print(f'Размер обучающей выборки: {features_train.shape}')
print(f'Размер тестовой выборки: {features_test.shape}')

Размер массива целевых значений обучающей выборки:(1928,)
Размер массива целевых значений тестовой выборки: (1286,)
Размер обучающей выборки: (1928, 3)
Размер тестовой выборки: (1286, 3)


### Выделение валидационной выборки из тестовой

In [12]:
#Разделим тестовую выборку на тестовую и валидационную
features_test, features_valid, target_test, target_valid = train_test_split(
    features_test, target_test, train_size=0.50,random_state=12345)

print(f'Размер массива целевых значений тестовой выборки: {target_test.shape}')
print(f'Размер массива целевых значений валидационной выборки:{target_valid.shape}')
print(f'Размер тестовой выборки:{features_test.shape}')
print(f'Размер валидационной выборки:{features_valid.shape}')

Размер массива целевых значений тестовой выборки: (643,)
Размер массива целевых значений валидационной выборки:(643,)
Размер тестовой выборки:(643, 3)
Размер валидационной выборки:(643, 3)


**Вывод:** <br>
- Из общих данных были выделены признаки 'futures' и 'target' <br>
- И общей совокупности данных были выделены три выборки:
  - обучающая ('features_train' и 'target_train') размером 1928 строк <br>
  - валидационная ('features_valid' и 'target_valid') размером 643 строки <br>
  - тестовая ('features_test' и 'target_test') размером 643 строки

<div class="alert alert-block alert-success">
<b>Успех:</b> Разбиение было сделано правильно. Радует, что была реализована проверка корректности разбиения!
</div>

## Исследование моделей

### Дерево решений

В качестве гиперпараметра возьмём глубину дерева.<br>
Максимальную глубину дерева будем исследовать в диапазоне от 2 до 10.

In [13]:
%%time
best_model_tree = None
best_depth_tree = 0
best_result_tree = 0
for depth in range (2,10):
    model = DecisionTreeClassifier(random_state=12345,max_depth=depth)
    model.fit(features_train,target_train)
    predictions_valid = model.predict(features_valid)
    result = accuracy_score(target_valid, predictions_valid)
    if result > best_result_tree:
        best_model_tree = model
        best_result_tree = result
        best_depth_tree = depth
        joblib.dump(best_model_tree, 'best_model_tree.joblib')

print("Глубина дерева:", best_depth_tree)
print("Лучшее значение accuracy:",best_result_tree.round(4))

Глубина дерева: 7
Лучшее значение accuracy: 0.7963
CPU times: user 64.9 ms, sys: 580 µs, total: 65.5 ms
Wall time: 337 ms


<div class="alert alert-block alert-success">
<b>Успех:</b> Подбор парамтеров был сделан верно.
</div>

### Случайный лес

В качестве гиперпараметра возьмём n_estimators(количество деревьев в лесу)

In [14]:
%%time

best_model_forest = None
best_result_forest = 0
for est in range(1, 51):
    model = RandomForestClassifier(random_state=12345, n_estimators=est)
    model.fit(features_train,target_train) 
    result = model.score(features_valid,target_valid) 
    if result > best_result_forest:
        best_model_forest = model
        best_result_forest = result
        joblib.dump(best_model_forest, 'best_model_forest.joblib')

print("Количество деревьев наилучшей модели Случайный лес:",est)
print("Accuracy наилучшей модели на валидационной выборке:", best_result_forest.round(4))

Количество деревьев наилучшей модели Случайный лес: 50
Accuracy наилучшей модели на валидационной выборке: 0.79
CPU times: user 3.83 s, sys: 21.2 ms, total: 3.85 s
Wall time: 4.54 s


<div class="alert alert-block alert-info">
<b>Совет: </b> Тут можно было настроить сразу несколько параметров.
</div>

<div class="alert alert-block alert-warning">
<b>Изменения:</b> Были внесены следующие изменения - Скопировал блок и перенёс его ниже, добавив параметры min_samples_split (Минимальное количество примеров для разделения) и min_samples_leaf (Минимальное количество объектов в листе) из соответстующего раздела тренажёра
</div>

In [15]:
%%time

best_model_forest = None
best_result_forest = 0
for i,split in enumerate(range(2,10)):
    for j,leaf in enumerate(range(1,4)):
        model_forest = RandomForestClassifier(random_state=12345, min_samples_split=split,min_samples_leaf=leaf) 
        model_forest.fit(features_train,target_train)
        
        result_forest = model_forest.score(features_valid,target_valid) 
        if result_forest > best_result_forest:
            best_model_forest = model_forest
            best_result_forest = result_forest
print("Accuracy наилучшей модели на валидационной выборке:",best_result_forest)  
print("Минимальное количество примеров для разделения:",split)
print("Минимальное количество объектов в листе:",leaf)
        
best_model_forest = None
best_result_forest = 0        
for est in range(1, 111):
    model = RandomForestClassifier(random_state=12345,min_samples_split=9,min_samples_leaf=3,n_estimators=est)
    model.fit(features_train,target_train)
    result = model.score(features_valid,target_valid)
    if result > best_result_forest:
        best_model_forest = model
        best_result_forest = result
        joblib.dump(best_model_forest, 'best_model_forest.joblib')

print("Количество деревьев наилучшей модели Случайный лес:",est)
print("Accuracy наилучшей модели на валидационной выборке:", best_result_forest)

Accuracy наилучшей модели на валидационной выборке: 0.8118195956454122
Минимальное количество примеров для разделения: 9
Минимальное количество объектов в листе: 3
Количество деревьев наилучшей модели Случайный лес: 110
Accuracy наилучшей модели на валидационной выборке: 0.8118195956454122
CPU times: user 22.9 s, sys: 172 ms, total: 23.1 s
Wall time: 24.1 s


<div class="alert alert-block alert-warning">
<b>Комментарий студента:</b> Даже не знаю, что и  думать...<br>
    - С одной стороны параметры min_samples_split и min_sample_leaf определённо улучшили качество модели. <br> 
    - С другой стороны прежний параметр n_estimators (количество деревьев в лесу) пришлось поднимать минимум до 100, чтобы получить то же самый accuracy, что и в случае, когда я его просто не указывал. Причём дальнейший его подъём (до 110) результат не улучшает. Складывается ощущение, что алгоритм и без меня знает сколько на самом деле нужно деревьев, а n_estimators позволяте просто сократить время расчёта, ухудшая при этом результат.
</div>


<div class="alert alert-block alert-success">
<b>Успех (ревью 2):</b> Если честно, то данных очень мало и они очень простые. Из-за этого очень большой эффект от случайности. В данном случае вряд ли получится выявить какую-то закономерность.
</div>

### Логистическая регрессия

In [16]:
%%time
model_log_reg = LogisticRegression(random_state=12345)
model_log_reg.fit(features_train,target_train) 
result_log_reg = model_log_reg.score(features_valid,target_valid) 

joblib.dump(model_log_reg, 'model_log_reg.joblib')

print("Accuracy наилучшей модели на валидационной выборке:",result_log_reg.round(4))

Accuracy наилучшей модели на валидационной выборке: 0.6983
CPU times: user 14.6 ms, sys: 3.98 ms, total: 18.6 ms
Wall time: 134 ms


**Выводы:** <br>
- Самым быстрым (12 ms) и наименее точным оказался метод Логистической регрессии. Accuracy = 0.6983 (не удовлетворяет заданию)
- Наиболее точным  и при этом достаточно быстрым (47 ms) оказался метод DecisionTreeClassifier(Дерева решений) . Accuracy = 0.7963.
- Самым медленным (3260 ms) и при этом немного уступающим в точности методу "Дерева решений" оказался метод RandomForestClassifier(Случайный лес). Accuracy = 0.7869.

<div class="alert alert-block alert-success">
<b>Успех:</b> Молодец, что попробовал разные модели в этом шаге!
</div>

## Проверка моделей на тестовой выборке

### Дерево решений

*Протестируем качество модели Дерева решений на тестовой выборке с выбранными гиперпараметрами max_depth=7* <br>

In [17]:
model_tree_test = DecisionTreeClassifier(random_state=12345,max_depth=7)
model_tree_test.fit(features_train,target_train)

test_predictions_tree = model_tree_test.predict(features_test)


print('Accuracy модели дерева решений на тестовой выборке:',accuracy_score(test_predictions_tree,target_test).round(4))

Accuracy модели дерева решений на тестовой выборке: 0.7714


### Случайный лес

*Протестируем качество модели Случайный лес на тестовой выборке.Выбрали оптимальный вариант с гиперпараметрами n_estimators = 50*

In [18]:
model_forest_test = RandomForestClassifier(random_state=12345, n_estimators=50) 
model_forest_test.fit(features_train,target_train)
test_predictions_forest = model_forest_test.predict(features_test)


print('Accuracy модели случайный лес на тестовой выборке:',accuracy_score(test_predictions_forest,target_test).round(4))

Accuracy модели случайный лес на тестовой выборке: 0.7792


**Выводы:** <br>
- На тестовой выборке и RandomForestClassifier(Случайный лес) показал чуть большую точность - 0.779, чем DecisionTreeClassifier(Дерево решений) - 0.771. 
Однако с  учетом того, что модель DecisionTreeClassifier(Дерево решений) работает значительно быстрее, целесообразнее выбрать ее в качестве алгоритма предсказания оптимальных тарифов, в случае большого набора данных.

<div class="alert alert-block alert-success">
<b>Успех:</b> Тестирование было сделаго правильно.
</div>

## Проверка модели на адекватность

*Проверку на  адекватность модели проведём с помощью классификатора DummyClassifier, который дает предсказания никак не опираясь на обучающие признаки. Аргумент strategy не меняем, по умолчанию будет стратегия, которая возвращает наиболее часто встречающийся целевой признак.*

In [20]:
from sklearn.dummy import DummyClassifier

dummy = DummyClassifier(strategy = 'uniform',random_state=12345).fit(features_train, target_train)
dummy_predict = dummy.predict(features_test)

print('Accuracy для случайных данных:',accuracy_score(target_test, dummy_predict))

Accuracy для случайных данных: 0.5038880248833593


**Вывод:**<br>
- Точность всех обученных моделей выше, чем точность при случайном методе.

<div class="alert alert-block alert-success">
<b>Успех:</b> Хорошо, что тут использовалась готова дамми модель!
</div>

<div class="alert alert-block alert-info">
<b>Совет: </b> Желательно было использовать стратегию most_frequent.
</div>

<div class="alert alert-block alert-warning">
<b>Изменения:</b> Были внесены следующие изменения - Скопировал блок выше и изменил параметр на most_frequent
</div>

In [21]:
from sklearn.dummy import DummyClassifier

dummy = DummyClassifier(strategy='most_frequent',random_state=12345).fit(features_train, target_train)
dummy_predict_freq = dummy.predict(features_test)

print('Accuracy для случайных данных:',accuracy_score(target_test, dummy_predict_freq))

Accuracy для случайных данных: 0.7060653188180405


<div class="alert alert-block alert-warning">
<b>Комментарий студента:</b> <br> 
    - Пришлось в обоих блоках добавить параметр стратегии, т.к. поменяв его однажды на most_frequent, последний становится параметром по умолчанию и оба блока выдают одинаковые значения, если в первом не указывать иной параметр в явном виде. <br>
    - на методе most_frequent (метод, который предсказывает наиболее частое значение в обучающем наборе) модель показала accuracy: 0.7061, что всё равно ниже, чем любая из моделей, обученных на наборе с признаками, кроме модели с логистической регрессией, которая с самого начала показала точность ниже требуемой в задании. Значит полученные в ходе работы модели делают прогнозы всё таки лучше, чем модели на случаных и наиболее часто встечающихся данных.
</div>


<div class="alert alert-block alert-success">
<b>Успех (ревью 2):</b> Отлично!
</div>

## Общий вывод

В ходе работы исходный датасет размером 3214 наблюдений был разделён на 2 выборки: <br>

- Обучающую, размером 2410 наблюдений; <br>
- Тестовую, размером 804 наблюдения (25% от датасета) <br>

В текущей задаче классификации были обучены и сравнены 3 различных модели-классификатора: дерево решений, случайный лес и логистическая регрессия.<br>

Получены следующие значения accuracy на тестовой выборке: <br>
- Дерево решений <br>
- - Accuracy = 0.7714 <br>
- Случайный лес <br>
- - Accuracy = 0.7792 <br>
- Логистическая регрессия (на обучающей выборке ввиду неудовлетворяющего заданию accuracy) <br>
- - Accuracy = 0.6983 <br>

Таким образом, наилучший результат показал алгоритм случайный лес, однако это самый медленный алгоритм.

<div class="alert alert-block alert-success">
<b>Успех:</b> Приятно видеть подробный вывод в конце проекта!
</div>